### ISSUE TITLE
Environment_DisableStaticSelfIllum doesn't get saved when using ent_lighteditor to save settings

### ISSUE THREAD

**Issue by WolfeStrider** [JonahSoldier/Gmod-Light-Environment-Editor#7]
If you cleanup the map and load a save with Environment_DisableStaticSelfIllum set to 1 using a ent_lighteditor it never gets set to 1

**Comment by JonahSoldier** [comment]
Should be fixed now. It was getting reset whenever the entity was spawned/loaded in.
